[project]
authors = ["TheS3b"]
channels = ["conda-forge", "nvidia", "pytorch"]
name = "SHS"
platforms = ["osx-arm64", "linux-64", "win-64"]
version = "0.1.0"

[system-requirements]
cuda = "12.2"

[tasks]

[dependencies]
python = "3.13.*"
pytorch = "*"
cuda-version = "12.2.*"
ipython = ">=9.0.2,<10"
ipykernel = ">=6.29.5,<7"
ipywidgets = ">=8.1.5,<9"
matplotlib = ">=3.10.1,<4"
pandas = ">=2.2.3,<3"
scikit-learn = ">=1.6.1,<2"
copier = ">=9.6.0,<10"
gymnasium = ">=0.26.3,<0.27"

[pypi-dependencies]
seiz_eeg = "*"

[target.win-64.dependencies]
[target.osx.pypi-dependencies]
