[workspace]
authors = ["theS3b>"]
channels = ["conda-forge"]
name = "shs_env"
platforms = ["linux-64", "win-64"]
version = "0.1.0"

[system-requirements]
cuda = "12.6"

[tasks]

[dependencies]
python = "3.10.*"
ipykernel = ">=6.29.5,<7"
ipywidgets = ">=8.1.5,<9"
pytorch = "*"
tqdm = "*"


[target.win-64.dependencies]